// Public surface: the drop-in wrapper + registry, the factory, and every icon.
export {
  AnimatedIcon,
  AnimateIcons,
  StaticIcons,
  type AnimatedIconHandle,
} from "./animated-icon";
export { createAnimatedIcon, type AnimatedIconProps } from "./create-animated-icon";
export * from "./icons/activity";
export * from "./icons/airplane";
export * from "./icons/align-left";
export * from "./icons/archive";
export * from "./icons/arrow-right";
export * from "./icons/arrow-up";
export * from "./icons/at-sign";
export * from "./icons/bell";
export * from "./icons/bold";
export * from "./icons/book-text";
export * from "./icons/brain";
export * from "./icons/building-office-2";
export * from "./icons/chart-line";
export * from "./icons/chart-no-axes-column-increasing";
export * from "./icons/chevrons-up-down";
export * from "./icons/circle-check";
export * from "./icons/circle-dashed";
export * from "./icons/circle-help";
export * from "./icons/clock";
export * from "./icons/cloud-backup";
export * from "./icons/cloud-cog";
export * from "./icons/cloud-upload";
export * from "./icons/compass";
export * from "./icons/computer-desktop";
export * from "./icons/connect";
export * from "./icons/copy";
export * from "./icons/corner-down-left";
export * from "./icons/credit-card";
export * from "./icons/cursor-click";
export * from "./icons/delete";
export * from "./icons/document-duplicate";
export * from "./icons/download";
export * from "./icons/file-text";
export * from "./icons/fingerprint";
export * from "./icons/flask";
export * from "./icons/gallery-vertical-end";
export * from "./icons/gauge";
export * from "./icons/grip-vertical";
export * from "./icons/history";
export * from "./icons/italic";
export * from "./icons/key";
export * from "./icons/layout-grid";
export * from "./icons/lifebuoy";
export * from "./icons/lock";
export * from "./icons/message-circle";
export * from "./icons/message-square-dashed";
export * from "./icons/message-square";
export * from "./icons/mic";
export * from "./icons/moon";
export * from "./icons/panel-left-close";
export * from "./icons/panel-left-open";
export * from "./icons/pen-tool";
export * from "./icons/phone-call";
export * from "./icons/phone";
export * from "./icons/plug-zap";
export * from "./icons/plus";
export * from "./icons/refresh-cw";
export * from "./icons/rocket";
export * from "./icons/rotate-ccw";
export * from "./icons/rotate-cw";
export * from "./icons/route";
export * from "./icons/search";
export * from "./icons/server";
export * from "./icons/settings";
export * from "./icons/shield-check";
export * from "./icons/sliders-horizontal";
export * from "./icons/sparkles";
export * from "./icons/square-pen";
export * from "./icons/sun";
export * from "./icons/trending-up";
export * from "./icons/upload";
export * from "./icons/user";
export * from "./icons/users";
export * from "./icons/webhook";
export * from "./icons/workflow";
export * from "./icons/wrench";
export * from "./icons/x";
